Add ray example

diff --git a/016_ray_cluster_pytorch/workflow.yaml b/016_ray_cluster_pytorch/workflow.yaml
--- a/016_ray_cluster_pytorch/workflow.yaml
+++ b/016_ray_cluster_pytorch/workflow.yaml
@@ -2,9 +2,7 @@ permissions:
   - '*'
 sessions:
   dashboard:
-    redirect: true
-
-
+    redirect: false
 jobs:
   auth:
     steps:
@@ -28,7 +26,9 @@ jobs:
               echo "Helm is already installed."
               echo "helm_cmd=$(which helm)" | tee -a $OUTPUTS
           fi
-        cleanup: rm -r linux-amd64
+        cleanup: |
+          rm -r linux-amd64
+          rm *.tar.gz
       - name: Install KubeRay Operator
         if: ${{inputs.deploy_ray_cluster == true }}
         env:
@@ -64,26 +64,37 @@ jobs:
         if: ${{inputs.deploy_ray_cluster == true }}
         run: |
           set -ex
-          wget  https://raw.githubusercontent.com/ray-project/ray/master/doc/source/cluster/kubernetes/configs/ray-cluster.gpu.yaml
-          if ! [ -f ray-cluster.gpu.yaml ]; then
-            echo "ERROR: ray-cluster.gpu.yaml file not found."
-          fi
+          cp 016_ray_cluster_pytorch/* .
           cluster_name=$(cat ray-cluster.gpu.yaml | grep name | head -n1 | awk '{ print $2 }')
           if [ -z "${cluster_name}" ]; then
             echo "ERROR: Unable to obtain Ray cluster's name."
             exit 1
           fi
-          echo "cluster_name=$(cluster_name)" | tee -a $OUTPUTS
+          echo "cluster_name=${cluster_name}" | tee -a $OUTPUTS
+
+          if kubectl get runtimeclass nvidia &>/dev/null; then
+            echo "nvidia RuntimeClass is available"
+            awk '
+            /^\s*workerGroupSpecs:/ { in_worker=1 }
+            in_worker && /^\s*spec:/ {
+              print $0
+              print "        runtimeClassName: nvidia"
+              in_worker=0
+              next
+            }
+            { print }
+            ' ray-cluster.gpu.yaml > temp.yaml && mv temp.yaml ray-cluster.gpu.yaml
+          fi
+          sed -i "s|rayproject/ray-ml:2.2.0-gpu|${{ inputs.k8s.ray_image }}|g" ray-cluster.gpu.yaml
           kubectl apply -f ray-cluster.gpu.yaml -n ${{ inputs.k8s.namespace }}
-        cleanup: |
-          kubectl delete -f ray-cluster.gpu.yaml -n ${{ inputs.k8s.namespace }}
-          kubectl delete raycluster raycluster -n ${{ inputs.k8s.namespace }}
+        cleanup: kubectl delete -f ray-cluster.gpu.yaml -n ${{ inputs.k8s.namespace }}
       - name: Wait for head pod
         env:
           cluster_name: ${{ needs.main.outputs.cluster_name }}
         if: ${{inputs.deploy_ray_cluster == true }}
         run: |
           set -ex
+          sleep 5
           log() {
             while true; do
               echo; echo
@@ -96,37 +107,60 @@ jobs:
           trap "kill ${log_pid}" EXIT
           kubectl wait pod \
             -n "${{ inputs.k8s.namespace }}" \
-            -l "rayCluster=${cluster_name},ray-node-type=head" \
+            -l ray.io/node-type=head \
             --for=condition=Ready \
             --timeout=10m
+
+          head_pod_name=$(kubectl get pods -n alvaro-k8s-testing | awk '{print $1}' | grep "${cluster_name}"-head)
+          if [ -z "${head_pod_name}" ]; then
+            echo "ERROR: Unable to obtain name of the head pod."
+            exit 1
+          fi
+          echo "head_pod_name=${head_pod_name}" | tee -a $OUTPUTS
+      - name: Select local dashboard port
+        if: ${{inputs.deploy_ray_cluster == true }}
+        run: |
+          # Select available port
+          dashboard_port=$(pw agent open-port)
+          echo "dashboard_port=${dashboard_port}" | tee -a $OUTPUTS
       - name: Create session for dashboard
         if: ${{inputs.deploy_ray_cluster == true }}
         uses: parallelworks/update-session
         with:
           remotePort: '8265'
+          localPort: ${{ needs.main.outputs.dashboard_port }}
           name: ${{ sessions.dashboard }}
           targetInfo:
             name: ${{ inputs.k8s.cluster }}
             namespace: ${{ inputs.k8s.namespace }}
-            resourceType: services
-            resourceName: "${{ needs.main.outputs.head_pod_name }}-head-svc"
-      - name: Test cluster
-        run: ray job submit --address http://localhost:8265 -- python -c "import ray; ray.init(); print(ray.cluster_resources())"
+            resourceType: pods
+            resourceName: ${{ needs.main.outputs.head_pod_name }}
       - name: Install ray
         run: |
           source /pw/.miniconda3/bin/activate
-          pip3 install -U "ray[default]"
-      - name: Run PyTorch ResNet Example
+          pip install --user -U "ray[default]"
+      - name: Test cluster
+        run: |
+          # Wait for session to connect
+          sleep 60
+          source /pw/.miniconda3/bin/activate
+          export PATH=$HOME/.local/bin:$PATH
+          ray job submit --address "http://localhost:${{ needs.main.outputs.dashboard_port }}" -- python -c "import ray; ray.init(); print(ray.cluster_resources())"
+      - name: Run PyTorch GPU Example
         run: |
           set -ex
-          # Download the Python script
-          curl https://raw.githubusercontent.com/ray-project/ray/master/doc/source/cluster/doc_code/pytorch_training_e2e_submit.py -o pytorch_training_e2e_submit.py
-          if ! [ -f pytorch_training_e2e_submit.py ]; then
-            echo "ERROR: pytorch_training_e2e_submit.py file not found."
-          fi
+          # Prevent transfer of these files to pod
+          echo helm* > .rayignore
+          echo logs/ >> .rayignore
+          echo linux-amd64/ >> .rayignore
+          
           # Submit the training job to your ray cluster
           source /pw/.miniconda3/bin/activate
-          python3 pytorch_training_e2e_submit.py
+          export PATH=$HOME/.local/bin:$PATH
+          sed -i "s|8265|${{ needs.main.outputs.dashboard_port }}|g" submit_job.py
+          job_id=$(python submit_job.py)
+          echo "Submitted Ray job with ID: $job_id"
+          ray job logs $job_id --address "http://127.0.0.1:${{ needs.main.outputs.dashboard_port }}" --follow
 
       - name: Wait for cancel
         if: ${{inputs.deploy_ray_cluster == true }}
@@ -165,10 +199,9 @@ jobs:
             default: 1.3.0
             hidden: ${{inputs.deploy_ray_cluster == false }}
             ignore: ${{ .hidden }}
-      prompts:
-        type: list
-        label: Prompt
-        template:
-          label: Prompt
-          type: editor
-          default: Futuristic hybrid computing control center with holographic dashboards displaying real-time AI training and simulations.
+          ray_image:
+            label: KubeRay Operator Version
+            type: string
+            default: rayproject/ray-ml:2.9.0-gpu
+            hidden: ${{inputs.deploy_ray_cluster == false }}
+            ignore: ${{ .hidden }}      
